### ISSUE TITLE
Create Database Entities

### ISSUE THREAD

**Issue by BigyaMaharjan** [BigyaMaharjan/Customer-Relationship-Management-CRM-System#5]
**1. Customer Table:**

Fields:
CustomerID (Primary Key)
CustomerName
Email
Mobile Number
Company
Department

**2. Lead Table:**

Fields:
LeadID (Primary Key)
CustomerID (Foreign Key referencing Customer table)
Lead Status (e.g., new, contacted, qualified, converted, lost)
AssignedTo (Foreign Key referencing User table for sales representative)

Relationship:
Many leads can be associated with single Customer.
Many Leads can be Assigned to One Sales Representative.

**3. Opportunity Table:**

Fields:
OpportunityID (Primary Key)
LeadID (Foreign Key referencing Lead table)
PotentialRevenue 
Probability of Closing 
Expected close date
OpportunityStatus (Values: prospecting, qualification, proposal, negotiation, closed won/lost) 

Relationship:
Many Opportunities can be associated with One Lead.

**4. User Table:**

Fields:
UserID (Primary Key)
Username
Password
RoleID (Foreign Key)

**5. Roles Table:**

Fields:
RoleID (Primary Key)
RoleName(Values: Manager, Sales Representative)

**Comment by psujit11** [comment]
DOne
